name: Real Estate Daily Check

on:
  schedule:
    # 한국 시간으로 매일 저녁 6시 (UTC 기준 오전 9시)
    - cron: '0 9 * * *'
  workflow_dispatch: # 직접 버튼 눌러서 테스트해 볼 수 있는 기능

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: 파이썬 설치
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 필요한 도구 설치
        run: |
          pip install requests PublicDataReader pandas

      - name: 실거래가 확인 로봇 실행
        env:
          SERVICE_KEY: ${{ secrets.SERVICE_KEY }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py
